#!/bin/bash
set -eo pipefail
set -xv

source /etc/lsb-release
: ${DISTRIB_ARCH:="$(dpkg --print-architecture)"}

# Hacks on hacks
case "$DISTRIB_CODENAME" in
    zesty|artful|bionic)
        echo "WARNING: $DISTRIB_CODENAME is not supported using the same URL scheme, trying to make this work using xenial packages." >&2
        DISTRIB_CODENAME="xenial"
        DISTRIB_RELEASE="16.04"
        ;;
esac

#
# [ ] Magic
# [X] More magic
#
# brb vomming
if [[ "$SALTY_APT_REPO" = *$* ]]; then
    # thrice to allow nesting
    for i in {1..3}; do
        eval SALTY_APT_REPO="${SALTY_APT_REPO}"
    done
fi

curl -sSLf "${SALTY_APT_REPO}/SALTSTACK-GPG-KEY.pub" \
  | apt-key add -

echo "deb $SALTY_APT_REPO $DISTRIB_CODENAME main" >> /etc/apt/sources.list.d/saltstack-official.list

lazy-apt --no-install-recommends \
    python-apt \
    ${SALTY_PACKAGES:?} \
    && :

